### PR TITLE
correctly displaying response statuses

### LINKED ISSUE #22: Status code always responds 0 when using proxy.
When I use proxy in combination with prometheus monitorying I always get status=0

### Expected behaviour
Caddy returns the correct status code to prometheus. eg: 200 or 404 and so on.

### Actual behaviour

Caddy always returns status code 0

### Other info
config file is like this.

```
https://site.url.example 
{
    tls admin@example.net
    prometheus 0.0.0.0:9180
    proxy / localhost:3000 {
        websocket
        transparent
    }
 }

### PR DESCRIPTION
**Pull request by achernyak**
This resolves #22

@miekg Could you please review?

My company is depending on this library in production. If you need any help with maintenance, please let me know.

This implementation was suggested in https://github.com/mholt/caddy/issues/1662.

### CODE REVIEW

**Comment by jancel** [comment]
+1

**Comment by miekg** [comment]
I've made to opposite change a while back: https://github.com/miekg/caddy-prometheus/commit/6f7750eab689fa5a0dd6770308b5c556f173e710
So we might need some testing for this to see if the normal stuff works. Also the reason why there is no integrating testing is because it is probably hard :-(

**Comment by achernyak** [comment]
Interesting. Maybe we need to use `rw.Status()` only if the status is 0. That would run it only for proxies or other requests that don't have a default status.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] correc..." ]
>Interesting. Maybe we need to use `rw.Status()` only if the status is 0. That would run it only for proxies or other requests that don't have a default status.

Yeah, thinking along the same lines.

Is there a light weight (without building all of caddy) to test this that you
can think of?

**Comment by achernyak** [comment]
I will work through this today and see what I can do for tests.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] correc..." ]
>I will work through this today and see what I can do for tests.

Nice, thank you!

**Comment by miekg** [comment]
Thinks this looks legit. Have you locally tested it without proxy and with proxy? And got 404 etc?

**Comment by achernyak** [comment]
Yes, local tests looked good for all proxy and non proxy responses. I also validated that the previous implementation always returned 200 on non proxies.

**Comment by miekg** [comment]
OK, let's worry about proper tests in a later PR.

**Comment by achernyak** [comment]
Thanks for the quick merge! I've scaffold the tests to a degree, just ran I to a couple issues that I'm trying to resolve now.

**Comment by achernyak** [comment]
@miekg what is the process for releases to caddy plugins? Specifically when would the updated version be available to install with caddy?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] correc..." ]
>@miekg what is the process for releases to caddy plugins? Specifically when would the updated version be available to install with caddy?

All manual :( Although @mholt made an REST interface. But, alas, I have zero
time to properly set this up.

Compiling caddy is not that hard btw  :) But I'll push some buttons.

**Comment by mholt** [comment]
Manual?? It used to be manual _before_ the new site. Now it's just a button push. And besides, git webhooks are almost ready. Would that be preferable?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] correc..." ]
>Manual?? It used to be manual _before_ the new site. Now it's just a button push. And besides, git webhooks are almost ready. Would that be preferable?

Yes! If we can do webhooks I'll set that up asap. (Nice!)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] correc..." ]
>@miekg what is the process for releases to caddy plugins? Specifically when would the updated version be available to install with caddy?

should be deployed on the caddy site

**Comment by achernyak** [comment]
@miekg Thank you so much!

**Pull request merged**
