### PR TITLE
caddy's importpath changed

### PR DESCRIPTION
**Pull request by miekg**
The import path changed, update to the new one.

### CODE REVIEW

**Comment by whalehub** [comment]
@miekg Can you publish a new release so that people can build Caddy from source with this plugin without having to specify the hash of this commit in their `go.mod` file?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/caddy-prometheus] caddy'..." ]
>@miekg Can you publish a new release so that people can build Caddy from source with this plugin without having to specify the hash of this commit in their `go.mod` file?

We've never released. "go get" will do this for you automatically

**Comment by hairyhenderson** [comment]
the `go.mod` file still references the old caddy path - that might be causing problems... I'll issue a PR soon.

**Comment by hairyhenderson** [comment]
See #56

**Comment by ghost** [comment]
@miekg Just tested it and can confirm that you're right. It looks like that step would only have been necessary if you had tagged one of your releases as "latest." As of v1.12.7, Go fetches the latest **version** by default and only resorts to the latest **commit** if there is no version tagged as "latest."

**Pull request merged**
