### PR TITLE
Add time to first write as response_latency_seconds (fixes #40)

### LINKED ISSUE #40: Record request latency
Currently we have the request duration. It would be nice to have the request latency as well. The closest proxy for this that I can think of is the time to the first Write() call on the response writer.

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by miekg** [comment]
Thanks! This should update the README.md as well though.

**Comment by calmh** [comment]
Sure. Do you want me to do that?

**Comment by calmh** [comment]
When looking at it now I realize that the other response metrics don't have the `family` and `proto` labels. Is this for historic reasons, or do you want to avoid having those on response metrics? I could see a point in having for example the `..._size_bytes` do accounting per proto and family, but the response latency I'm adding here shouldn't be dependent on either of those so perhaps cleanest to avoid the labels?

**Comment by calmh** [comment]
I did that, and went one step further and added the `status` label to all response metrics. It makes sense at least for the latency metric, where 404s are probably instantaneous and not interesting, etc.

**Pull request merged**
